import type { MapFeature, MapOptions, MapStyle } from '../mapgen';
import type { Mission } from './types';

function map(style: MapStyle, width = 1600, height = 900, features?: MapFeature[]): MapOptions {
  return { width, height, waterLevel: height - 40, style, ...(features ? { features } : {}) };
}

/**
 * The 30 campaign missions: three chapters of ten with a rising difficulty curve (bot skill 1→5,
 * more and tougher enemies, restricted arsenals, special maps and physics).
 */
export const MISSIONS: Mission[] = [
  // ── Chapter 1: Sunny Shores ───────────────────────────────────────────────────────────────
  {
    id: 'c1-01',
    chapter: 1,
    index: 1,
    seed: 'camp:c1-01',
    map: map('hills', 1300, 800),
    player: { units: 3 },
    enemies: [{ units: 2, hp: 60 }],
    bot: 1,
    config: { windEnabled: false },
    stars: [{ kind: 'turns', max: 5 }, { kind: 'noLosses' }],
  },
  {
    id: 'c1-02',
    chapter: 1,
    index: 2,
    seed: 'camp:c1-02',
    map: map('flats', 1400, 800),
    player: { units: 3 },
    enemies: [{ units: 2, hp: 80 }],
    bot: 1,
    stars: [
      { kind: 'turns', max: 6 },
      { kind: 'hpLeft', min: 220 },
    ],
  },
  {
    id: 'c1-03',
    chapter: 1,
    index: 3,
    seed: 'camp:c1-03',
    map: map('hills', 1400, 850),
    player: { units: 3, only: ['grenade'] },
    enemies: [{ units: 2, hp: 80 }],
    bot: 1,
    config: { windEnabled: false },
    stars: [{ kind: 'noLosses' }, { kind: 'turns', max: 7 }],
  },
  {
    id: 'c1-04',
    chapter: 1,
    index: 4,
    seed: 'camp:c1-04',
    map: map('islands'),
    player: { units: 3 },
    enemies: [{ units: 3, hp: 80 }],
    bot: 1,
    stars: [
      { kind: 'turns', max: 8 },
      { kind: 'hpLeft', min: 200 },
    ],
  },
  {
    id: 'c1-05',
    chapter: 1,
    index: 5,
    seed: 'camp:c1-05',
    map: map('hills', 1600, 900, [
      { kind: 'rock', x: 520, y: 380, r: 30 },
      { kind: 'rock', x: 800, y: 340, r: 36 },
      { kind: 'rock', x: 1080, y: 380, r: 30 },
    ]),
    player: { units: 3 },
    enemies: [{ units: 3, hp: 90 }],
    bot: 2,
    stars: [{ kind: 'onlyWeapon', weapon: 'bazooka' }, { kind: 'noLosses' }],
  },
  {
    id: 'c1-06',
    chapter: 1,
    index: 6,
    seed: 'camp:c1-06',
    map: map('flats'),
    player: { units: 3 },
    enemies: [{ units: 3 }],
    bot: 2,
    config: { gravityPct: 60 },
    stars: [
      { kind: 'turns', max: 8 },
      { kind: 'hpLeft', min: 180 },
    ],
  },
  {
    id: 'c1-07',
    chapter: 1,
    index: 7,
    seed: 'camp:c1-07',
    map: map('towers'),
    player: { units: 3 },
    enemies: [{ units: 3 }],
    bot: 2,
    stars: [{ kind: 'noLosses' }, { kind: 'turns', max: 9 }],
  },
  {
    id: 'c1-08',
    chapter: 1,
    index: 8,
    seed: 'camp:c1-08',
    map: map('hills'),
    player: { units: 3 },
    enemies: [{ units: 3 }],
    bot: 2,
    config: { windScale: 200 },
    startWind: 8,
    stars: [
      { kind: 'onlyWeapon', weapon: 'grenade' },
      { kind: 'hpLeft', min: 160 },
    ],
  },
  {
    id: 'c1-09',
    chapter: 1,
    index: 9,
    seed: 'camp:c1-09',
    map: map('islands', 1800, 900),
    player: { units: 3 },
    enemies: [{ units: 4, hp: 70 }],
    bot: 2,
    stars: [{ kind: 'turns', max: 10 }, { kind: 'noLosses' }],
  },
  {
    id: 'c1-10',
    chapter: 1,
    index: 10,
    seed: 'camp:c1-10',
    map: map('hills'),
    player: { units: 3 },
    enemies: [{ units: 1, hp: 260 }],
    bot: 3,
    stars: [
      { kind: 'turns', max: 6 },
      { kind: 'hpLeft', min: 200 },
    ],
  },
  // ── Chapter 2: Iron Isles ─────────────────────────────────────────────────────────────────
  {
    id: 'c2-01',
    chapter: 2,
    index: 1,
    seed: 'camp:c2-01',
    map: map('islands'),
    player: { units: 3, only: ['bazooka', 'shotgun'] },
    enemies: [{ units: 3 }],
    bot: 3,
    stars: [{ kind: 'turns', max: 8 }, { kind: 'noLosses' }],
  },
  {
    id: 'c2-02',
    chapter: 2,
    index: 2,
    seed: 'camp:c2-02',
    map: map('towers'),
    player: { units: 3 },
    enemies: [{ units: 3 }],
    bot: 3,
    stars: [
      { kind: 'hpLeft', min: 180 },
      { kind: 'turns', max: 10 },
    ],
  },
  {
    id: 'c2-03',
    chapter: 2,
    index: 3,
    seed: 'camp:c2-03',
    map: map('cavern'),
    player: { units: 3 },
    enemies: [{ units: 3 }],
    bot: 3,
    stars: [{ kind: 'noLosses' }, { kind: 'turns', max: 10 }],
  },
  {
    id: 'c2-04',
    chapter: 2,
    index: 4,
    seed: 'camp:c2-04',
    map: map('flats'),
    player: { units: 3 },
    enemies: [{ units: 4, hp: 80 }],
    bot: 3,
    config: { gravityPct: 140 },
    stars: [
      { kind: 'turns', max: 10 },
      { kind: 'hpLeft', min: 150 },
    ],
  },
  {
    id: 'c2-05',
    chapter: 2,
    index: 5,
    seed: 'camp:c2-05',
    map: map('islands'),
    player: { units: 4, only: ['grenade', 'cluster', 'bazooka'], ammo: { cluster: 5 } },
    enemies: [{ units: 3 }],
    bot: 3,
    stars: [{ kind: 'onlyWeapon', weapon: 'cluster' }, { kind: 'noLosses' }],
  },
  {
    id: 'c2-06',
    chapter: 2,
    index: 6,
    seed: 'camp:c2-06',
    map: map('towers'),
    player: { units: 4 },
    enemies: [{ units: 4 }],
    bot: 3,
    config: { crateChance: 100 },
    stars: [
      { kind: 'hpLeft', min: 220 },
      { kind: 'turns', max: 12 },
    ],
  },
  {
    id: 'c2-07',
    chapter: 2,
    index: 7,
    seed: 'camp:c2-07',
    map: map('hills'),
    player: { units: 3 },
    enemies: [{ units: 3 }],
    bot: 4,
    config: { windScale: 250 },
    stars: [{ kind: 'noLosses' }, { kind: 'turns', max: 10 }],
  },
  {
    id: 'c2-08',
    chapter: 2,
    index: 8,
    seed: 'camp:c2-08',
    map: map('cavern', 1600, 900, [
      { kind: 'girder', x: 560, y: 420, w: 120 },
      { kind: 'girder', x: 920, y: 420, w: 120 },
    ]),
    player: { units: 3 },
    enemies: [{ units: 4, hp: 80 }],
    bot: 4,
    stars: [
      { kind: 'turns', max: 11 },
      { kind: 'hpLeft', min: 150 },
    ],
  },
  {
    id: 'c2-09',
    chapter: 2,
    index: 9,
    seed: 'camp:c2-09',
    map: map('islands'),
    player: { units: 2, hp: 160 },
    enemies: [{ units: 3, hp: 70 }],
    bot: 4,
    stars: [{ kind: 'noLosses' }, { kind: 'hpLeft', min: 200 }],
  },
  {
    id: 'c2-10',
    chapter: 2,
    index: 10,
    seed: 'camp:c2-10',
    map: map('towers'),
    player: { units: 4 },
    enemies: [{ units: 2, hp: 150 }],
    bot: 4,
    stars: [{ kind: 'turns', max: 10 }, { kind: 'noLosses' }],
  },
  // ── Chapter 3: Deep Dark ──────────────────────────────────────────────────────────────────
  {
    id: 'c3-01',
    chapter: 3,
    index: 1,
    seed: 'camp:c3-01',
    map: map('cavern'),
    player: { units: 4, hp: 120 },
    enemies: [{ units: 2 }, { units: 2 }],
    bot: 4,
    stars: [{ kind: 'noLosses' }, { kind: 'turns', max: 10 }],
  },
  {
    id: 'c3-02',
    chapter: 3,
    index: 2,
    seed: 'camp:c3-02',
    map: map('islands'),
    player: { units: 3 },
    enemies: [{ units: 4 }],
    bot: 4,
    config: { gravityPct: 55 },
    stars: [
      { kind: 'hpLeft', min: 180 },
      { kind: 'turns', max: 11 },
    ],
  },
  {
    id: 'c3-03',
    chapter: 3,
    index: 3,
    seed: 'camp:c3-03',
    map: map('towers', 1800, 900),
    player: { units: 4 },
    enemies: [{ units: 4 }],
    bot: 5,
    stars: [{ kind: 'noLosses' }, { kind: 'turns', max: 12 }],
  },
  {
    id: 'c3-04',
    chapter: 3,
    index: 4,
    seed: 'camp:c3-04',
    map: map('cavern'),
    player: {
      units: 4,
      hp: 120,
      only: ['grenade', 'cluster', 'dynamite', 'mortar'],
      ammo: { dynamite: 3, mortar: 4 },
    },
    enemies: [{ units: 3, hp: 70 }],
    bot: 5,
    stars: [
      { kind: 'hpLeft', min: 150 },
      { kind: 'turns', max: 12 },
    ],
  },
  {
    id: 'c3-05',
    chapter: 3,
    index: 5,
    seed: 'camp:c3-05',
    map: map('flats', 1800, 900),
    player: { units: 4, hp: 130 },
    enemies: [{ units: 2 }, { units: 2 }],
    bot: 5,
    config: { crateChance: 100 },
    stars: [{ kind: 'turns', max: 10 }, { kind: 'noLosses' }],
  },
  {
    id: 'c3-06',
    chapter: 3,
    index: 6,
    seed: 'camp:c3-06',
    map: map('hills'),
    player: { units: 4, hp: 120 },
    enemies: [{ units: 3, hp: 80 }],
    bot: 5,
    config: { windScale: 250 },
    startWind: -9,
    stars: [
      { kind: 'onlyWeapon', weapon: 'grenade' },
      { kind: 'hpLeft', min: 120 },
    ],
  },
  {
    id: 'c3-07',
    chapter: 3,
    index: 7,
    seed: 'camp:c3-07',
    map: map('islands', 2000, 900),
    player: { units: 3, hp: 170 },
    enemies: [{ units: 3 }, { units: 3 }],
    bot: 5,
    stars: [{ kind: 'noLosses' }, { kind: 'turns', max: 14 }],
  },
  {
    id: 'c3-08',
    chapter: 3,
    index: 8,
    seed: 'camp:c3-08',
    map: map('cavern'),
    player: { units: 4 },
    enemies: [{ units: 4 }],
    bot: 5,
    config: { gravityPct: 140 },
    stars: [
      { kind: 'hpLeft', min: 150 },
      { kind: 'turns', max: 12 },
    ],
  },
  {
    id: 'c3-09',
    chapter: 3,
    index: 9,
    seed: 'camp:c3-09',
    map: map('towers', 2000, 900),
    player: { units: 4 },
    enemies: [{ units: 5, hp: 80 }],
    bot: 5,
    stars: [{ kind: 'noLosses' }, { kind: 'turns', max: 14 }],
  },
  {
    id: 'c3-10',
    chapter: 3,
    index: 10,
    seed: 'camp:c3-10',
    map: map('hills', 1800, 900, [
      { kind: 'metal', x: 880, y: 250, w: 40, h: 14 },
      { kind: 'rock', x: 600, y: 420, r: 34 },
      { kind: 'rock', x: 1200, y: 420, r: 34 },
    ]),
    player: { units: 4, hp: 150 },
    enemies: [{ units: 3, hp: 160 }],
    bot: 5,
    stars: [
      { kind: 'turns', max: 14 },
      { kind: 'hpLeft', min: 200 },
    ],
  },
];

export const CHAPTERS = [1, 2, 3] as const;
export type Chapter = (typeof CHAPTERS)[number];
/** Missions completed in chapter N that unlock chapter N + 1. */
export const CHAPTER_UNLOCK_COUNT = 7;

export function missionById(id: string): Mission | undefined {
  return MISSIONS.find((m) => m.id === id);
}

export function chapterMissions(chapter: number): Mission[] {
  return MISSIONS.filter((m) => m.chapter === chapter);
}

/** The mission after `id` in campaign order, or undefined after the last one. */
export function nextMission(id: string): Mission | undefined {
  const i = MISSIONS.findIndex((m) => m.id === id);
  return i >= 0 ? MISSIONS[i + 1] : undefined;
}
